
import java.sql.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;


import javax.swing.table.DefaultTableModel;



public class Billing extends javax.swing.JFrame {
    private static java.sql.Connection con;
    
    static int i = 1;
    static float total_amount = 0;
    static float received_amount = 0;
    static float amount_to_be_paid = 0;
    static float remaining_bal = 0;
    static float rate;
    static int  quantityTbl;
    static float price;
    static long barcode_tbl;
    static int rowTable;
    static HashMap<String, Integer> barcodes = new HashMap<>();
    static ArrayList<String> multiple_barcodes = new ArrayList<>();
    
    /**
     * Creates new form Billing
     */
    public Billing() {
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Product Name", "Rate", "Quantity", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 1050, 230));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel3.setText("Amount to be paid");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 240, 50));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 48)); // NOI18N
        jLabel5.setText("BILLING  SECTION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 500, 70));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Print Receipt");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 540, 190, 40));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Sales Invoice");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 117, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Bill Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Mobile");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Bill Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setText("Checkout");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 90, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel2.setText("Payment Mode");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 100, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel6.setText("Payment Received");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 120, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setText("Reamining Bal");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 140, 30));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 130, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("Discount Amount");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 200, 40));

        jTextField7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextField7.setText("0");
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, 160, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel13.setText("Total Amount");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 180, 60));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, 210, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel14.setText("Barcode");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 110, 30));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, 190, 60));

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 100, 210, 60));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Calculate Amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 190, 40));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit Card", "Credit Card", "UPI" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 160, 30));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 160, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 140, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 160, 40));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("Pay Later");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, 190, 40));

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 620, 190, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel19.setText("Amount Due");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, 150, 40));

        jTextField2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 650, 160, 40));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Name");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 60, 30));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton6.setText("Delete Bill");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 430, 150, 40));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 190, 30));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton5.setText("Remove");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 330, 150, 40));
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\santo\\Documents\\NetBeansProjects\\BillGenerator\\src\\BG.png")); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setBounds(0, 0, 1294, 727);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        
        
        
        String barcode = jTextField8.getText();
        
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","root",""); 
            System.out.println("Success");
            Statement st = con.createStatement();
            String q = "Select * from productdetails where barcode = "+barcode;
            
            
            
            ResultSet rs =st.executeQuery(q);
            
            while(rs.next()){
                String rate = String.valueOf(rs.getFloat("rate")) ;
                String product_name = rs.getString("Productname");
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                
                int quan = rs.getInt("quantity");
                if(quan < 50){
                    GEmailSender es = new GEmailSender();
                    es.sendEmail("siddhartha2704@gmail.com", "billingSystem.gmail.com", "Add Products to Inventory", "The quantity of "+product_name+" is less than 50 please add products to the inventory");
                }
                if(!multiple_barcodes.contains(barcode)){
                    
                    multiple_barcodes.add(barcode);
                    System.out.println(multiple_barcodes);
                    barcodes.put(barcode,1);
                    
                    String tbData[] = {String.valueOf(i++),product_name,rate,String.valueOf(barcodes.get(barcode)),rate};
                    
                    tblModel.addRow(tbData);
                }
                else{
                    System.out.println("here");
                    int a = barcodes.get(barcode);
                    barcodes.replace(barcode,++a);
                    tblModel.setValueAt(barcodes.get(barcode), multiple_barcodes.indexOf(barcode), 3);
                    tblModel.fireTableCellUpdated(multiple_barcodes.indexOf(barcode), 3);
                    tblModel.setValueAt(barcodes.get(barcode)*rs.getFloat("rate"), multiple_barcodes.indexOf(barcode), 4);
                    tblModel.fireTableCellUpdated(multiple_barcodes.indexOf(barcode), 4);
                }
                
                total_amount += rs.getFloat("rate");
                
                jLabel15.setText(String.valueOf(total_amount));
            }
          
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        } 
        jTextField8.setText("");
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        
        try {
           
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(bill_id) FROM bill");
            rs.next();
            rs.getString("MAX(bill_id)");
            if (rs.getString("MAX(bill_id)") == null) {
                jLabel17.setText("B-0000001");     
            } else {
                long id = Long.parseLong(rs.getString("MAX(bill_id)").substring(2, rs.getString("MAX(bill_id)").length()));
                id++;
                jLabel17.setText("B-" + String.format("%07d", id));
            }
            
            
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        } 
        
        
        LocalDate date = LocalDate.now();
        jLabel18.setText(String.valueOf(date));
        if(jTextField7.getText() == null){
            JOptionPane.showMessageDialog(null, "Discount is not det");
        }
        else{
            int discount = Integer.parseInt(jTextField7.getText());
            amount_to_be_paid = total_amount-discount;
            jLabel16.setText(String.valueOf(amount_to_be_paid));
            
        }
        
        if(jTextField6.getText() == null){
            JOptionPane.showMessageDialog(null, "Received amount is not set");
        }
        else{
            received_amount = Float.parseFloat(jTextField6.getText());
            remaining_bal = received_amount - amount_to_be_paid;
            jLabel20.setText(String.valueOf(remaining_bal));
            
        }
        
        
        
        if(Double.parseDouble(jLabel20.getText())<0){
        jTextField2.setText(String.valueOf(Double.parseDouble(jLabel20.getText())*-1));
        }
        else
            jTextField2.setText("0");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Statement st = con.createStatement();

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","root",""); 
            System.out.println("Success");
            
            String sql = "insert into bill values(?,?,?,?,?)";
            PreparedStatement pt = con.prepareStatement(sql);
            pt.setString(1, jLabel17.getText());
            pt.setString(2, (String) jComboBox1.getSelectedItem());
            pt.setString(3, jLabel16.getText());
            pt.setString(4, jTextField1.getText());
            pt.setString(5, jLabel18.getText());
            pt.executeUpdate();
            
            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
            int rowsToRemove = tblModel.getRowCount();
            
            for(int i=0;i<rowsToRemove;i++){
            String p_name = (String) tblModel.getValueAt(i, 1);
            int quan = Integer.parseInt((String) tblModel.getValueAt(i, 3));
            String q1 = "UPDATE productdetails SET quantity = quantity - "+quan+" WHERE productname = '"+p_name+"'";
            int rs1 = st.executeUpdate(q1);
            
            }
            
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        int rowsToRemove = tblModel.getRowCount();
        for(int i = rowsToRemove-1;i>=0;i--){
            tblModel.removeRow(i);
        }
        
        
        barcodes.clear();
        multiple_barcodes.clear();
        total_amount = 0;
        received_amount = 0;
        amount_to_be_paid = 0;
        remaining_bal = 0;
        i=1;
        jTextField1.setText("");
        jTextField6.setText("");
        jTextField7.setText("0");
        jLabel20.setText("");
        jLabel17.setText("");
        jLabel15.setText("");
        jLabel16.setText("");
        jTextField3.setText("");
        jTextField2.setText("0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        {
        setVisible(false);
                new Home().setVisible(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(Double.parseDouble(jLabel20.getText()) < 0.0){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","root","12210708"); 
            System.out.println("Success");
            
            String sql = "insert into outstanding values(?,?,?,?,?,?,?)";
            PreparedStatement pt = con.prepareStatement(sql);
            pt.setString(1, jLabel17.getText());
            pt.setString(2, jTextField3.getText());
            pt.setString(3, jTextField1.getText());
            pt.setString(4, jLabel16.getText());
            pt.setString(5, jTextField6.getText());
            pt.setString(6, jTextField2.getText());
            pt.setString(7, jLabel18.getText());
            pt.executeUpdate();
            
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Due is 0 cannot add");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        if(barcodes.get(multiple_barcodes.get(rowTable)) == 1){
           
           barcodes.remove(multiple_barcodes.get(rowTable));
           multiple_barcodes.remove(rowTable);
       }
       else{
           System.out.println("Reducing");
       int n = barcodes.get(multiple_barcodes.get(rowTable));
       barcodes.replace(multiple_barcodes.get(rowTable),--n);
       }
        
       DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        
       if(Integer.parseInt(String.valueOf(tblModel.getValueAt(rowTable, 3))) == 1)
       {
                      System.out.println("In if");

            //tblModel.setValueAt(String.valueOf(barcodes.get(multiple_barcodes.get(rowTable))), rowTable, 3);
            //tblModel.setValueAt(price-rate, rowTable, 4);
            amount_to_be_paid = (amount_to_be_paid - rate);
            total_amount = (total_amount - rate);
            jLabel15.setText(Float.toString(total_amount));
            tblModel.removeRow(rowTable);
       }
       else{
           System.out.println("In Else");
       tblModel.setValueAt(String.valueOf(barcodes.get(multiple_barcodes.get(rowTable))), rowTable, 3);
       tblModel.setValueAt(price-rate, rowTable, 4);
       amount_to_be_paid = (amount_to_be_paid - rate);
       total_amount = (total_amount - rate);
       jLabel15.setText(Float.toString(total_amount));
       }
       rate=0;
       quantityTbl=0;
       price =0;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        rowTable = jTable1.getSelectedRow();
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();  
       
        rate = Float.parseFloat((String) tblModel.getValueAt(rowTable, 2));
        System.out.println(rate);
        Class<?> variableClass = tblModel.getValueAt(rowTable, 3).getClass();
        System.out.println(variableClass);
        quantityTbl = Integer.parseInt(String.valueOf(tblModel.getValueAt(rowTable, 3)) );
        
        System.out.println(quantityTbl);
        price = Float.parseFloat(String.valueOf(tblModel.getValueAt(rowTable, 4)));
        System.out.println(price);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        int rowsToRemove = tblModel.getRowCount();
        for(int i = rowsToRemove-1;i>=0;i--){
            tblModel.removeRow(i);
        }
        
        
        barcodes.clear();
        multiple_barcodes.clear();
        total_amount = 0;
        received_amount = 0;
        amount_to_be_paid = 0;
        remaining_bal = 0;
        i=1;
        jTextField1.setText("");
        jTextField6.setText("");
        jTextField7.setText("0");
        jLabel20.setText("");
        jLabel17.setText("");
        jLabel15.setText("");
        jLabel16.setText("");
        jTextField3.setText("");
        jTextField2.setText("0");
    }//GEN-LAST:event_jButton6ActionPerformed

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
