/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;

import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class Inventory extends javax.swing.JFrame {
    private static java.sql.Connection con;
    
    
    public Inventory() {
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Barcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        product_name = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        New = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No.", "Name", "Rate", "Quantity", "Barcode"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 1150, 300));

        Barcode.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarcodeActionPerformed(evt);
            }
        });
        getContentPane().add(Barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 390, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NAME");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 160, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("QUANTITY ADDED");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 170, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PRICE");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 160, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BARCODE");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 170, 40));

        product_name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_nameActionPerformed(evt);
            }
        });
        getContentPane().add(product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 390, 40));

        Price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceActionPerformed(evt);
            }
        });
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 390, 40));

        Quantity.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }
        });
        getContentPane().add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 390, 40));

        Delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 160, 50));

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 580, 160, 50));

        New.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        New.setText("NEW");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        getContentPane().add(New, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 160, 50));

        Update.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 160, 50));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton1.setText("GET DATABASE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, 160, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SR NO.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 100, 40));

        jTextField1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 250, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton2.setText("SUGGESTIONS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 650, 170, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\santo\\Documents\\NetBeansProjects\\BillGenerator\\src\\BG.png")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarcodeActionPerformed

    private void product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_nameActionPerformed

    private void PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceActionPerformed

    private void QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       {
        setVisible(false);
                new Home(). setVisible(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        
        String name = product_name.getText();
        int quantity = Integer.parseInt(Quantity.getText());
        double price = Double.parseDouble(Price.getText());
        long barcode = Long.parseLong(Barcode.getText());
        
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","(database username)", "(database password")); 
            System.out.println("Success");
            Statement st = con.createStatement();
            String sql = "INSERT INTO productdetails (`ProductName`, `rate`, `Quantity`, `Barcode`)" +
                         "VALUES" +
                         "('"+name+"',"+price+"," +quantity+", "+barcode+")";
            int rs = st.executeUpdate(sql);
            
            
            con.close();
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        
    }//GEN-LAST:event_NewActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        //String name = product_name.getText();
        //int quantity = Integer.parseInt(Quantity.getText());
        //double price = Double.parseDouble(Price.getText());
        //long barcode = Long.parseLong(Barcode.getText());
        
        String sr_no = jTextField1.getText();

        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","(database username)", "(database password")); 
            //System.out.println("Success");
            Statement st = con.createStatement();
            if(Quantity.getText()!=null && Price.getText()== null){
                int quantity = Integer.parseInt(Quantity.getText());
                
                String sql = "UPDATE productdetails SET `Quantity` = `Quantity` + " + quantity + " WHERE `Sr No` = " + sr_no;
                st.executeUpdate(sql);
            }
            else if(Price.getText()!= null && Quantity.getText()==null){
                double price = Double.parseDouble(Price.getText());
                String sql1 = "UPDATE productdetails SET `rate` = " + price + " WHERE `Sr No` = " + sr_no;
                st.executeUpdate(sql1);
            }
            else {
                int quantity = Integer.parseInt(Quantity.getText());
                double price = Double.parseDouble(Price.getText());
                String sql = "UPDATE productdetails SET `Quantity` = `Quantity` + " + quantity + " WHERE `Sr No` = " + sr_no;
                st.executeUpdate(sql);
                String sql1 = "UPDATE productdetails SET `rate` = " + price + " WHERE `Sr No` = " + sr_no;
                st.executeUpdate(sql1);
            }
                         
            
            
            System.out.println("Updated");
            con.close();
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
    }//GEN-LAST:event_UpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        int rowsToRemove = tblModel.getRowCount();
        for(int i = rowsToRemove-1;i>=0;i--){
            tblModel.removeRow(i);
        }
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","(database username)", "(database password")); 
            //System.out.println("Success");
            Statement st = con.createStatement();
            String sql = "select * from productdetails";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                int n = rs.getInt("sr no");
                String name = rs.getString("ProductName");
                Double rate = rs.getDouble("rate");
                int quantity = rs.getInt("quantity");
                long barcode = rs.getLong("barcode");
                
                String row[] = {String.valueOf(n),name,String.valueOf(rate),String.valueOf(quantity),String.valueOf(barcode)};
                tblModel.addRow(row);
               
            }
             System.out.println("Database given");
             con.close();
            } catch (ClassNotFoundException | SQLException ex) {
                System.out.println(ex.getMessage());
            }
        
        product_name.setText("");
        Price.setText("");
        Barcode.setText("");
        Quantity.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        
        String name = product_name.getText();
        //int quantity = Integer.parseInt(Quantity.getText());
        //double price = Double.parseDouble(Price.getText());
        //long barcode = Long.parseLong(Barcode.getText());
        String sr_no = jTextField1.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","(database username)", "(database password")); 
            System.out.println("Success");
            Statement st = con.createStatement();
            String sql = "DELETE FROM productdetails WHERE `Sr No` = " + sr_no;

            int rs = st.executeUpdate(sql);
            
            
            con.close();
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        ArrayList<String> list = new ArrayList<>();
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        
        int rowsToRemove = tblModel.getRowCount();
        for(int i = rowsToRemove-1;i>=0;i--){
            tblModel.removeRow(i);
        }
        
        String txt = product_name.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","(database username)", "(database password")); 
            System.out.println("Success");
            Statement st = con.createStatement();
            String sql = "select * from productdetails";
            
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                int sum = 0;
                int n = rs.getInt("sr no");
                String name_table = rs.getString("ProductName");
                //Double rate_table = rs.getDouble("rate");
                //int quantity_table = rs.getInt("quantity");
                //long barcode_table = rs.getLong("barcode");
                
                int len = txt.length();
                for(int i=0;i<len;i++){
                    if(txt.toLowerCase().charAt(i) == name_table.toLowerCase().charAt(i)){
                        sum++;
                    }
                }
                if(sum == len)
                    list.add(name_table);
                
            }
            System.out.println("Out");
            System.out.println(list);
            for (String list1 : list) {
                String get = "Select * from productdetails where productname = '"+list1+"'";
                ResultSet rs1 = st.executeQuery(get);
                while(rs1.next())
                {
                int n1 = rs1.getInt("sr no");
                String name1 = rs1.getString("ProductName");
                Double rate1 = rs1.getDouble("rate");
                int quantity1 = rs1.getInt("quantity");
                long barcode1 = rs1.getLong("barcode");
                System.out.println(n1);
                String row[] = {String.valueOf(n1),name1,String.valueOf(rate1),String.valueOf(quantity1),String.valueOf(barcode1)};
                tblModel.addRow(row);
                }
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        product_name.setText(tblModel.getValueAt(row, 1).toString());
        Price.setText(tblModel.getValueAt(row, 2).toString());
        //Quantity.setText(tblModel.getValueAt(row, 3).toString());
        Barcode.setText(tblModel.getValueAt(row, 4).toString());
        jTextField1.setText(tblModel.getValueAt(row, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Barcode;
    private javax.swing.JButton Delete;
    private javax.swing.JButton New;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField product_name;
    // End of variables declaration//GEN-END:variables
}
