
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author santo
 */
public class Outstanding extends javax.swing.JFrame {
    private static java.sql.Connection con;
    
    String bill_no; 
    String name;
    String ph_no;
    int total_amt;
    double paid_amt;
    double due_amt;
    String date;
    public Outstanding() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill ID", "Name", "Phone No.", "Total Amt", "Paid Amt", "Due Amt", "Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 43, 1260, 410));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ph Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 150, 40));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 310, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setText("Get Database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, 170, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 600, 170, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, 170, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 170, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Amount Paid");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, 130, 40));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, 310, 40));

        jButton5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, 150, 40));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 310, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Bill No.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 100, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\santo\\Documents\\NetBeansProjects\\BillGenerator\\src\\BG.png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        int rowsToRemove = tblModel.getRowCount();
        for(int i = rowsToRemove-1;i>=0;i--){
            tblModel.removeRow(i);
        }
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","(database username)", "(database password")); 
            //System.out.println("Success");
            Statement st = con.createStatement();
            String sql = "select * from outstanding";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String bill_no1 = rs.getString("bill_no");
                String name1 = rs.getString("Name");
                String ph_no1 = rs.getString("phone_no");
                int total_amt1 = rs.getInt("total_amount");
                double paid_amt1 = rs.getDouble("paid_amount");
                double due_amt1 = rs.getDouble("due_amount");
                String date1 = rs.getString("due_date");
                
                
                String row[] = {bill_no1,name1,ph_no1,String.valueOf(total_amt1),String.valueOf(paid_amt1),String.valueOf(due_amt1),date1};
                tblModel.addRow(row);
               
            }
             System.out.println("Database given");
             con.close();
            } catch (ClassNotFoundException | java.sql.SQLException ex) {
                System.out.println(ex.getMessage());
            }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ArrayList<String> list = new ArrayList<>();
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        
        int rowsToRemove = tblModel.getRowCount();
        for(int i = rowsToRemove-1;i>=0;i--){
            tblModel.removeRow(i);
        }
        
        String no = jTextField1.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","(database username)", "(database password")); 
            System.out.println("Success");
            Statement st = con.createStatement();
            String sql = "select * from outstanding";
            
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                int sum = 0;
                //int n = rs.getInt("sr no");
                String bill_no = rs.getString("bill_no");
                String name_table = rs.getString("phone_no");
                //Double rate_table = rs.getDouble("rate");
                //int quantity_table = rs.getInt("quantity");
                //long barcode_table = rs.getLong("barcode");
                
                int len = no.length();
                for(int i=0;i<len;i++){
                    if(no.charAt(i) == name_table.charAt(i)){
                        sum++;
                    }
                }
                if(sum == len)
                    list.add(bill_no);
                
            }
            System.out.println("Out");
            System.out.println(list);
            for (String list1 : list) {
                String get = "Select * from outstanding where bill_no = '"+list1+"'";
                ResultSet rs1 = st.executeQuery(get);
                while(rs1.next())
                {
                String bill_no1 = rs1.getString("bill_no");
                String name1 = rs1.getString("Name");
                String ph_no1 = rs1.getString("phone_no");
                int total_amt1 = rs1.getInt("total_amount");
                double paid_amt1 = rs1.getDouble("paid_amount");
                double due_amt1 = rs1.getDouble("due_amount");
                String date1 = rs1.getString("due_date");
                
                
                String row[] = {bill_no1,name1,ph_no1,String.valueOf(total_amt1),String.valueOf(paid_amt1),String.valueOf(due_amt1),date1};
                tblModel.addRow(row);
                }
            }
            con.close();
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        int rowsToRemove = tblModel.getRowCount();
        for(int i = rowsToRemove-1;i>=0;i--){
            tblModel.removeRow(i);
        }
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","(database username)", "(database password")); 
            //System.out.println("Success");
            Statement st = con.createStatement();
            String sql = "DELETE FROM outstanding WHERE bill_no = '"+bill_no+"'";
            int rs = st.executeUpdate(sql);
            
            
             System.out.println("Database given");
             con.close();
            } catch (ClassNotFoundException | java.sql.SQLException ex) {
                System.out.println(ex.getMessage());
            }
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","(database username)", "(database password")); 
            //System.out.println("Success");
            Statement st = con.createStatement();
            String sql = "select * from outstanding";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String bill_no1 = rs.getString("bill_no");
                String name1 = rs.getString("Name");
                String ph_no1 = rs.getString("phone_no");
                int total_amt1 = rs.getInt("total_amount");
                double paid_amt1 = rs.getDouble("paid_amount");
                double due_amt1 = rs.getDouble("due_amount");
                String date1 = rs.getString("due_date");
                
                
                String row[] = {bill_no1,name1,ph_no1,String.valueOf(total_amt1),String.valueOf(paid_amt1),String.valueOf(due_amt1),date1};
                tblModel.addRow(row);
               
            }
             System.out.println("Database given");
             con.close();
            } catch (ClassNotFoundException | java.sql.SQLException ex) {
                System.out.println(ex.getMessage());
            }
        
        bill_no = "";
       name = "";
    }//GEN-LAST:event_jButton2ActionPerformed
        
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int row = jTable1.getSelectedRow();
       DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();  
       bill_no = (String) tblModel.getValueAt(row, 0);
       name = (String) tblModel.getValueAt(row, 2);
       jTextField1.setText(tblModel.getValueAt(row, 2).toString());
       jTextField3.setText(tblModel.getValueAt(row, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        int rowsToRemove = tblModel.getRowCount();
        for(int i = rowsToRemove-1;i>=0;i--){
            tblModel.removeRow(i);
        }
        
        
        String bill_id = jTextField3.getText();
        double amount_paid = Double.parseDouble(jTextField2.getText());
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","(database username)", "(database password")); 
            //System.out.println("Success");
            Statement st = con.createStatement();
            String sql = "UPDATE outstanding SET paid_amount = paid_amount + "+amount_paid+", due_amount = due_amount - "+amount_paid+" WHERE bill_no = '"+bill_id+"'";
            int rs = st.executeUpdate(sql);
            
            
             System.out.println("Updated");
             con.close();
            } catch (ClassNotFoundException | java.sql.SQLException ex) {
                System.out.println(ex.getMessage());
            }
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/petsglorious","(database username)", "(database password")); 
            //System.out.println("Success");
            Statement st = con.createStatement();
            String sql = "select * from outstanding";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String bill_no1 = rs.getString("bill_no");
                String name1 = rs.getString("Name");
                String ph_no1 = rs.getString("phone_no");
                int total_amt1 = rs.getInt("total_amount");
                double paid_amt1 = rs.getDouble("paid_amount");
                double due_amt1 = rs.getDouble("due_amount");
                String date1 = rs.getString("due_date");
                
                
                String row[] = {bill_no1,name1,ph_no1,String.valueOf(total_amt1),String.valueOf(paid_amt1),String.valueOf(due_amt1),date1};
                tblModel.addRow(row);
               
            }
             System.out.println("Database given");
             con.close();
            } catch (ClassNotFoundException | java.sql.SQLException ex) {
                System.out.println(ex.getMessage());
            }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
                new Home(). setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Outstanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Outstanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Outstanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Outstanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Outstanding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
